# @package _global_
id: 1
hydra:
  run:
    dir: ${BASE_DIR}/
dataset:
  train_proportion: 1.0
  test_proportion: 0.3
  standardize: false
  name: OpenMLDataset
  dataset_id: 1510
  respect_train_test: true
experiment:
  n_runs: 1
  random_seed: -1
  debug: true
  save_data_until: 10
  # loss: TPRLoss
  loss: BalancedAccuracy
  # loss: BalancedAccuracyLoss
  log_every: 1
  save_every: 5
  abort_test_after: 1000
risk_estimators:
- TrueRiskEstimator
# - BiasedRiskEstimator
- FancyUnbiasedRiskEstimator
# - QuadratureRiskEstimator
# - TrueUnseenRiskEstimator
acquisition_functions:
# - TrueLossAcquisition: null
# - RandomAcquisition: null
- SelfSurrogateAcquisitionEntropy: null
# - ClassifierAcquisitionEntropy: null
# - AnySurrogateAcquisitionEntropy: LazySurrEnsemble
acquisition:
  sample: true
  animate: true
  animate_until: 10
  lazy_save: true
  uniform_clip: true
  uniform_clip_val: 0.2
  lazy_save_schedule:
  - 0
  - 100
  - 300
  - 500
  - 700
model:
  name: SKLearnModel
  # type: GradientBoostingClassifier
  type: RandomForestClassifier
  # type: DecisionTreeClassifier
  # type: LogisticRegression
  calibrated: true
  skip_fit_debug: model.pth
  skip_fit_debug_relative: true
  save_path: model.pth
  num_classes: 2
  training_cfg:
    validation_set_size: 5000
    stratify_val: true
    max_epochs: 200
    learning_rate: 0.1
    batch_size: 128
    num_workers: 4
    pin_memory: true
    early_stopping_epochs: 200
    weight_decay: 0.0005
    optimizer: cifar
    scheduler: devries
    transforms: cifar
    testing_cfg:
      batch_size: 1000
acquisition_configs:
  LazySurrEnsemble:
    keep_constant: true
    name: SKLearnModel
    calibrated: true
    n_models: 10
    efficient: true
    save_path: ensembles/model_{}.pth
    skip_fit_debug: ensembles/model_{}.pth
    skip_fit_debug_relative: true
    num_classes: 2
    debug_mnist: false
    lazy: true
    lazy_schedule: []
    training_cfg:
      validation_set_size: 5000
      stratify_val: true
      max_epochs: 200
      learning_rate: 0.1
      batch_size: 128
      num_workers: 4
      pin_memory: true
      early_stopping_epochs: 200
      weight_decay: 0.0005
      optimizer: cifar
      scheduler: devries
      transforms: cifar
    testing_cfg:
      batch_size: 1000
